# -*- coding: utf-8 -*-
"""LaptopPrices_StarTech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCg6JokAqPybDNrs71bMf1K8YU09xk2l
"""

# import libraries
import requests
from bs4 import BeautifulSoup as bs

product_names = []
processor_types = []
product_rams = []
product_storages = []
product_displays = []
product_prices = []

# Initialize page number
page = 1

# Initialize a counter for the iterations
iteration = 0

while iteration < 5:
    # Generate URL for the current page
    url = f'https://www.startech.com.bd/laptop-notebook/laptop?filter_status=7&limit=90&page={page}'


    # Query the website and return the html to the variable ‘response’
    response = requests.get(url).text

    soup = bs(response, "html.parser")

    # Find all product details
    for product in soup.find_all('div', class_='p-item-details'):
      # If no products are found, we've reached the end of the pages
      if not product:
          break

      # Get product name and link
      product_name_link = product.find('h4', class_='p-item-name').find('a')
      if product_name_link:
          product_name = product_name_link.text
          product_names.append(product_name)
          print(f'Product Name: {product_name}')

      # Get product attributes
      product_attributes = product.find('div', class_='short-description').find_all('li')
      for attribute in product_attributes:
          attribute_text = attribute.text
          if 'Processor' in attribute_text:
              processor_type = attribute_text.replace("Processor: ", "").replace("\r", "")
              processor_types.append(processor_type)
              print(f'Processor: {processor_type}')

          elif 'RAM' in attribute_text and 'Storage' in attribute_text:
              ram_storage = attribute_text.replace("\r", "").split("Storage:")
              ram = ram_storage[0].replace("RAM: ", "")
              storage = ram_storage[1]
              product_rams.append(ram)
              product_storages.append(storage)
              print(f'RAM: {ram}')
              print(f'Storage: {storage}')

          elif 'Display' in attribute_text:
              product_display = attribute_text.replace("Display: ", "").replace("\r", "")
              product_displays.append(product_display)
              print(f'Display Size (Inch): {attribute_text.replace("Display: ", "")}')

      # Get product price
      product_price = product.find('div', class_='p-item-price').find('span')
      if product_price:
          price = product_price.text.replace('৳', '')
          product_prices.append(price)
          print(f'Product Price: {price}')

    # Increment the page number after each iteration
    page += 1

    # Increment the iteration counter
    iteration += 1

# print(soup)

product_names[:5]

processor_types[:5]

product_rams[:5]

product_storages[:5]

product_displays[:5]

product_prices[:5]

product_prices_len = len(product_prices)
product_prices_len

"""# Export to Excel CSV"""

import csv

# Prepare data for CSV
rows = zip(product_names, processor_types, product_rams, product_storages, product_displays, product_prices)

# Write to CSV
with open('LaptopPrices_StarTech.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(["Product Name", "Processor Type", "RAM", "Storage", "Display", "Price"])  # writing headers
    for row in rows:
        writer.writerow(row)

from google.colab import files

# Download the file to your computer
files.download('LaptopPrices_StarTech.csv')

import pandas as pd
LaptopPrices_StarTech = pd.read_csv("LaptopPrices_StarTech.csv")

LaptopPrices_StarTech.head()

LaptopPrices_StarTech.shape

"""**As we can see, a dataset consisting 1786 rows and 9 columns of different laptop attribues has successfully been created.**"""